/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "surface-variant": "#e2e3e1",
        "outline-variant": "#c3c8c1",
        "on-surface-variant": "#434843",
        "tertiary-container": "#736f65",
        "surface-container": "#eeeeec",
        "surface-container-high": "#e8e8e6",
        "on-tertiary-fixed-variant": "#4a473e",
        "secondary-fixed": "#ffdbcf",
        "primary-fixed": "#d1e8d5",
        "outline": "#737873",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "tertiary": "#5a574d",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#e8e2d6",
        "on-tertiary-fixed": "#1e1c14",
        "on-surface": "#1a1c1b",
        "on-tertiary-container": "#f9f3e7",
        "surface-container-highest": "#e2e3e1",
        "surface-bright": "#f9f9f7",
        "on-secondary-container": "#773319",
        "tertiary-fixed-dim": "#cbc6ba",
        "background": "#f9f9f7",
        "secondary-container": "#fd9e7b",
        "surface-container-low": "#f4f4f2",
        "surface-dim": "#dadad8",
        "inverse-on-surface": "#f1f1ef",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#ffb59b",
        "on-secondary-fixed-variant": "#763218",
        "on-secondary-fixed": "#380d00",
        "surface-tint": "#4f6354",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#5f7464",
        "on-primary": "#ffffff",
        "surface": "#f9f9f7",
        "inverse-surface": "#2f3130",
        "on-secondary": "#ffffff",
        "inverse-primary": "#b5ccb9",
        "on-primary-container": "#e2f9e5",
        "primary": "#475b4c",
        "on-background": "#1a1c1b",
        "on-primary-fixed-variant": "#374b3d",
        "on-primary-fixed": "#0c1f13",
        "secondary": "#94492d",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#b5ccb9"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "md": "24px",
        "base": "8px",
        "sm": "12px",
        "xs": "4px",
        "gutter": "24px",
        "lg": "40px",
        "margin-mobile": "16px",
        "xl": "64px",
        "container-max": "1280px"
      },
      "fontFamily": {
        "headline-sm": ["Montserrat"],
        "body-sm": ["Inter"],
        "label-sm": ["Inter"],
        "headline-lg": ["Montserrat"],
        "body-lg": ["Inter"],
        "headline-md": ["Montserrat"],
        "headline-lg-mobile": ["Montserrat"],
        "label-md": ["Inter"],
        "body-md": ["Inter"]
      },
      "fontSize": {
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "500"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-sm": ["11px", {"lineHeight": "14px", "fontWeight": "500"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "headline-lg-mobile": ["26px", {"lineHeight": "32px", "fontWeight": "600"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
